GET http://0.0.0.0:8000/api/bot
Content-Type: application/json

{
    "object": "whatsapp_business_account",
    "entry": [
        {
            "id": "105738109234424",
            "changes": [
                {
                    "value": {
                        "messaging_product": "whatsapp",
                        "metadata": {
                            "display_phone_number": "2348188885192",
                            "phone_number_id": "159854773878577"
                        },
                        "contacts": [
                            {
                                "profile": {
                                    "name": "Maxi Tech"
                                },
                                "wa_id": "2347016791512"
                            }
                        ],
                        "messages": [
                            {
                                "from": "2347016791512",
                                "id": "wamid.HBgNMjM0OTA1NzYxOTg2ORUCABIYFjNFQjAzRDFENUIzMjRBNTJGNTA4NjYA",
                                "timestamp": "1689454241",
                                "text": {
                                    "body": "1"
                                },
                                "type": "text"
                            }
                        ]
                    },
                    "field": "messages"
                }
            ]
        }
    ]
}